services:
  nginx:
    image: nginx:latest
    container_name: nginxSecu
    ports:
      - "80:80"  # Port hôte : Port conteneur
      - "443:443" #Port https	
    volumes:
      - ./src:/var/www/php  # Montage du répertoire src de l'hôte dans /var/www/php du conteneur
      - ./.docker/nginx/conf.d/default.d:/etc/nginx/conf.d/default.conf  # Configuration personnalisée de Nginx
      #- ./certificat/:/etc/letsencrypt/live/ciel-broceliande.myasustor.com/  #Montage des certificats et clefs privée de mon site 
        #- /etc/letsencrypt/:/etc/letsencrypt/
        #user: "1000:1000"
    working_dir: /var/www/php  # Répertoire de travail
    depends_on:
      - php  # Dépend du service php
    networks:
      - mynet


  # Service PHP image
  php:
    image: php:8.2-fpm  # Utilise l'image php 8.2
    container_name: phpSecu
    working_dir: /var/www/php  # Répertoire de travail
    volumes:
      - ./src:/var/www/php  # Montage du répertoire src de l'hôte dans /var/www/php du conteneur
    #depends_on:
        #  - mysql  # Dépend du service MySQL
    networks:
      - mynet

  # Service MySQL
  #EN COMMENTAIRE CAR PAS UTILE POUR LA MANIP
  #mysql:
  #  image: mysql/mysql-server:latest
  #  container_name: mysqlSecu
  #  environment:
  #    MYSQL_ROOT_PASSWORD: root
  #    MYSQL_ROOT_HOST: '%'  # Autorise la connexion de n'importe quel hôte
  #  ports:
  #    - "3306:3306"  # Port hôte : Port conteneur
  #  volumes:
  #    - ./mysqldata:/var/lib/mysql  # Connecte le volume mysqldata au répertoire de données de MySQL
  #  networks:
  #    - mynet

  # Service PhpMyAdmin
  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin:latest
  #  container_name: phpmyadminSecu
  #  ports:
  #    - "8080:80"  # Port hôte : Port conteneur
  #  environment:
  #    PMA_HOST: mysql  # Hôte de la base de données MySQL
  #    PMA_PORT: 3306  # Port de la base de données MySQL
  #  networks:
  #    - mynet

volumes:
  mysqldata:  # Définition du volume pour les données MySQL
    driver: local

networks:
  mynet:  # Définition du réseau

